name: CI - Backend Spring Boot

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"

  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Compilar back-end
        working-directory: backend
        run: mvn clean install -DskipTests